// 分類配置，包含色彩、圖標、描述等
export const categoryConfig = {
  'history': { 
    name: 'History',
    name_en: 'History',
    description: 'State formation, empire, revolution, Soviet rule, and the post-1991 federation.',
    description_en: 'State formation, empire, revolution, Soviet rule, and the post-1991 federation.',
    icon: '📜',
    color: '#92400e',
    colorLight: '#f59e0b20',
    gradient: 'linear-gradient(135deg, #92400e, #d97706)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Spasskaya_Tower_and_St_Basil%27s_Cathedral.jpg/640px-Spasskaya_Tower_and_St_Basil%27s_Cathedral.jpg',
  },
  'geography': { 
    name: 'Geography',
    name_en: 'Geography',
    description: 'From Baltic shorelines to Pacific volcanoes, Arctic tundra to southern steppe.',
    description_en: 'From Baltic shorelines to Pacific volcanoes, Arctic tundra to southern steppe.',
    icon: '🗺️',
    color: '#065f46',
    colorLight: '#059f4620',
    gradient: 'linear-gradient(135deg, #065f46, #10b981)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Lena_Pillars.jpg/640px-Lena_Pillars.jpg',
  },
  'culture': { 
    name: 'Culture',
    name_en: 'Culture',
    description: 'Literature, religion, memory, language, and the practices that shape Russian identity.',
    description_en: 'Literature, religion, memory, language, and the practices that shape Russian identity.',
    icon: '🎭',
    color: '#7c3aed',
    colorLight: '#7c3aed20',
    gradient: 'linear-gradient(135deg, #7c3aed, #a855f7)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Saint_Basil%27s_Cathedral_in_Moscow.jpg/640px-Saint_Basil%27s_Cathedral_in_Moscow.jpg',
  },
  'food': { 
    name: 'Food',
    name_en: 'Food',
    description: 'Regional cuisines shaped by climate, trade routes, religion, and empire.',
    description_en: 'Regional cuisines shaped by climate, trade routes, religion, and empire.',
    icon: '🍜',
    color: '#ea580c',
    colorLight: '#ea580c20',
    gradient: 'linear-gradient(135deg, #ea580c, #f97316)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Borscht_served.jpg/640px-Borscht_served.jpg',
  },
  'art': { 
    name: 'Art',
    name_en: 'Art',
    description: 'Icons, avant-garde movements, museums, cinema, design, and public memory.',
    description_en: 'Icons, avant-garde movements, museums, cinema, design, and public memory.',
    icon: '🎨',
    color: '#be185d',
    colorLight: '#be185d20',
    gradient: 'linear-gradient(135deg, #be185d, #ec4899)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/The_State_Hermitage_Museum_2014.jpg/640px-The_State_Hermitage_Museum_2014.jpg',
  },
  'music': { 
    name: 'Music',
    name_en: 'Music',
    description: 'Classical traditions, folk repertoires, Soviet songwriting, rock, rap, and regional scenes.',
    description_en: 'Classical traditions, folk repertoires, Soviet songwriting, rock, rap, and regional scenes.',
    icon: '🎵',
    color: '#0891b2',
    colorLight: '#0891b220',
    gradient: 'linear-gradient(135deg, #0891b2, #06b6d4)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Bolshoi_Theatre.jpg/640px-Bolshoi_Theatre.jpg',
  },
  'technology': { 
    name: 'Technology',
    name_en: 'Technology',
    description: 'Energy systems, aerospace, nuclear engineering, mathematics, software, and digital platforms.',
    description_en: 'Energy systems, aerospace, nuclear engineering, mathematics, software, and digital platforms.',
    icon: '💻',
    color: '#1d4ed8',
    colorLight: '#1d4ed820',
    gradient: 'linear-gradient(135deg, #1d4ed8, #3b82f6)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Vostochny_Cosmodrome.jpg/640px-Vostochny_Cosmodrome.jpg',
  },
  'nature': { 
    name: 'Nature',
    name_en: 'Nature',
    description: 'Taiga forests, Arctic coastlines, mountain chains, rivers, and biodiversity under pressure.',
    description_en: 'Taiga forests, Arctic coastlines, mountain chains, rivers, and biodiversity under pressure.',
    icon: '🌿',
    color: '#15803d',
    colorLight: '#15803d20',
    gradient: 'linear-gradient(135deg, #15803d, #22c55e)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Lake_Baikal_Southwestern_shore.jpg/640px-Lake_Baikal_Southwestern_shore.jpg',
  },
  'people': { 
    name: 'People',
    name_en: 'People',
    description: 'Writers, scientists, rulers, dissidents, artists, and entrepreneurs who shaped the country.',
    description_en: 'Writers, scientists, rulers, dissidents, artists, and entrepreneurs who shaped the country.',
    icon: '👥',
    color: '#b45309',
    colorLight: '#b4530920',
    gradient: 'linear-gradient(135deg, #b45309, #f59e0b)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Lomonosov_on_a_stamp.jpg/400px-Lomonosov_on_a_stamp.jpg',
  },
  'society': { 
    name: 'Society',
    name_en: 'Society',
    description: 'Public institutions, urban life, education, media, demography, and social change.',
    description_en: 'Public institutions, urban life, education, media, demography, and social change.',
    icon: '🏛️',
    color: '#475569',
    colorLight: '#47556920',
    gradient: 'linear-gradient(135deg, #475569, #64748b)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Moscow_Metro_Komsomolskaya.jpg/640px-Moscow_Metro_Komsomolskaya.jpg',
  },
  'economy': { 
    name: 'Economy',
    name_en: 'Economy',
    description: 'Energy, metals, agriculture, logistics, sanctions, and the challenge of diversification.',
    description_en: 'Energy, metals, agriculture, logistics, sanctions, and the challenge of diversification.',
    icon: '📊',
    color: '#c2410c',
    colorLight: '#c2410c20',
    gradient: 'linear-gradient(135deg, #c2410c, #ea580c)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Moscow_City_2019.jpg/400px-Moscow_City_2019.jpg',
  },
  'lifestyle': { 
    name: 'Lifestyle',
    name_en: 'Lifestyle',
    description: 'Seasonal rhythms, housing, transport, leisure, holidays, and everyday urban and rural routines.',
    description_en: 'Seasonal rhythms, housing, transport, leisure, holidays, and everyday urban and rural routines.',
    icon: '🏠',
    color: '#4d7c0f',
    colorLight: '#4d7c0f20',
    gradient: 'linear-gradient(135deg, #4d7c0f, #65a30d)',
    cover: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Russian_dacha.jpg/640px-Russian_dacha.jpg',
  }
};

export type CategoryKey = keyof typeof categoryConfig;

export function getCategoryConfig(category: string): typeof categoryConfig[CategoryKey] | null {
  return categoryConfig[category as CategoryKey] || null;
}
